### ISSUE TITLE
plugin incompatible with neovim 0.6

### ISSUE THREAD

**Issue by tex** [smolck/command-completion.nvim#3]
nvim-0.6.1

```
Error detected while processing /home/milan/.config/nvim/init.vim:
line   24:
E5108: Error executing lua ...ugged/command-completion.nvim/lua/command-completion.lua:223: attempt to index field 'keymap' (a nil value)
stack traceback:
        ...ugged/command-completion.nvim/lua/command-completion.lua:223: in function 'setup'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by smolck** [comment]
Ah, `vim.keymap` is a 0.7-only feature I guess, probably should've mentioned that in the README.

I'll leave this open for now though and see if I can get it working with 0.6.1 without too much hassle.

**Comment by smolck** [comment]
@tex Mind giving #4 a test? Seems to work for me locally but just want to make sure.

**Comment by tex** [comment]
It works. But looking at amount of changes needed, I guess you just should write to readme that it needs 0.7 and I would wait until my distro gets it :)

Not sure if it is relevant to this change, but I see lot of
W19: Deleting augroup that is still in use

And it is fairly easy to break it: it shows the menu when it shouldn't and then it is impossible to get rid of it (and it is empty).

**Comment by smolck** [comment]
Yeah okay, I don’t really feel good about that PR anyways. So, 0.7+ only it is :)
